import { KeyDefinition } from './uyghurLayout';

// 标准 QWERTY 布局（英文 & 拼音共用）
export const qwertyLayout: KeyDefinition[][] = [
  [
    { key: '`', en: '`', shift: '~', type: 'normal', width: 1 },
    { key: '1', en: '1', shift: '!', type: 'normal', width: 1 },
    { key: '2', en: '2', shift: '@', type: 'normal', width: 1 },
    { key: '3', en: '3', shift: '#', type: 'normal', width: 1 },
    { key: '4', en: '4', shift: '$', type: 'normal', width: 1 },
    { key: '5', en: '5', shift: '%', type: 'normal', width: 1 },
    { key: '6', en: '6', shift: '^', type: 'normal', width: 1 },
    { key: '7', en: '7', shift: '&', type: 'normal', width: 1 },
    { key: '8', en: '8', shift: '*', type: 'normal', width: 1 },
    { key: '9', en: '9', shift: '(', type: 'normal', width: 1 },
    { key: '0', en: '0', shift: ')', type: 'normal', width: 1 },
    { key: '-', en: '-', shift: '_', type: 'normal', width: 1 },
    { key: '=', en: '=', shift: '+', type: 'normal', width: 1 },
    { key: 'Backspace', en: 'Backspace', type: 'special', width: 2 },
  ],
  [
    { key: 'Tab', en: 'Tab', type: 'special', width: 1.5 },
    { key: 'q', en: 'q', shift: 'Q', type: 'normal', width: 1 },
    { key: 'w', en: 'w', shift: 'W', type: 'normal', width: 1 },
    { key: 'e', en: 'e', shift: 'E', type: 'normal', width: 1 },
    { key: 'r', en: 'r', shift: 'R', type: 'normal', width: 1 },
    { key: 't', en: 't', shift: 'T', type: 'normal', width: 1 },
    { key: 'y', en: 'y', shift: 'Y', type: 'normal', width: 1 },
    { key: 'u', en: 'u', shift: 'U', type: 'normal', width: 1 },
    { key: 'i', en: 'i', shift: 'I', type: 'normal', width: 1 },
    { key: 'o', en: 'o', shift: 'O', type: 'normal', width: 1 },
    { key: 'p', en: 'p', shift: 'P', type: 'normal', width: 1 },
    { key: '[', en: '[', shift: '{', type: 'normal', width: 1 },
    { key: ']', en: ']', shift: '}', type: 'normal', width: 1 },
    { key: '\\', en: '\\', shift: '|', type: 'normal', width: 1.5 },
  ],
  [
    { key: 'CapsLock', en: 'CapsLock', type: 'special', width: 1.75 },
    { key: 'a', en: 'a', shift: 'A', type: 'normal', width: 1 },
    { key: 's', en: 's', shift: 'S', type: 'normal', width: 1 },
    { key: 'd', en: 'd', shift: 'D', type: 'normal', width: 1 },
    { key: 'f', en: 'f', shift: 'F', type: 'normal', width: 1 },
    { key: 'g', en: 'g', shift: 'G', type: 'normal', width: 1 },
    { key: 'h', en: 'h', shift: 'H', type: 'normal', width: 1 },
    { key: 'j', en: 'j', shift: 'J', type: 'normal', width: 1 },
    { key: 'k', en: 'k', shift: 'K', type: 'normal', width: 1 },
    { key: 'l', en: 'l', shift: 'L', type: 'normal', width: 1 },
    { key: ';', en: ';', shift: ':', type: 'normal', width: 1 },
    { key: "'", en: "'", shift: '"', type: 'normal', width: 1 },
    { key: 'Enter', en: 'Enter', type: 'special', width: 2.25 },
  ],
  [
    { key: 'Shift', en: 'ShiftLeft', type: 'special', width: 2.25 },
    { key: 'z', en: 'z', shift: 'Z', type: 'normal', width: 1 },
    { key: 'x', en: 'x', shift: 'X', type: 'normal', width: 1 },
    { key: 'c', en: 'c', shift: 'C', type: 'normal', width: 1 },
    { key: 'v', en: 'v', shift: 'V', type: 'normal', width: 1 },
    { key: 'b', en: 'b', shift: 'B', type: 'normal', width: 1 },
    { key: 'n', en: 'n', shift: 'N', type: 'normal', width: 1 },
    { key: 'm', en: 'm', shift: 'M', type: 'normal', width: 1 },
    { key: ',', en: ',', shift: '<', type: 'normal', width: 1 },
    { key: '.', en: '.', shift: '>', type: 'normal', width: 1 },
    { key: '/', en: '/', shift: '?', type: 'normal', width: 1 },
    { key: 'Shift', en: 'ShiftRight', type: 'special', width: 2.75 },
  ],
  [
    { key: 'ControlLeft', en: 'Ctrl', type: 'special', width: 1.25 },
    { key: 'MetaLeft', en: 'Win', type: 'special', width: 1.25 },
    { key: 'AltLeft', en: 'Alt', type: 'special', width: 1.25 },
    { key: 'Space', en: 'Space', type: 'special', width: 6 },
    { key: 'AltRight', en: 'Alt', type: 'special', width: 1.25 },
    { key: 'MetaRight', en: 'Win', type: 'special', width: 1.25 },
    { key: 'ContextMenu', en: 'Menu', type: 'special', width: 1.25 },
    { key: 'ControlRight', en: 'Ctrl', type: 'special', width: 1.25 },
  ],
];
