# 构建阶段
FROM public.ecr.aws/docker/library/node:18-alpine AS build

WORKDIR /app

# 设置 npm 镜像以提升速度
RUN npm config set registry https://registry.npmmirror.com

COPY package.json ./
RUN npm install

COPY . .
RUN npm run build

# 运行阶段
FROM public.ecr.aws/docker/library/nginx:stable-alpine

# 将构建好的静态文件复制到 Nginx 的默认目录
COPY --from=build /app/dist /usr/share/nginx/html

# 暴露 80 端口
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
